#!/usr/bin/perl
#sub d{$_=shift;$_=`namecoind name_show d/$_`=~/"value"\s*:\s*"(.*?[^\\])"/s?$1:"404";s/\\"/"/g;s/\\n/\n/g;$_}

# tmp v sub that just reads from file
sub v {
	my $file = shift;
	if ( open FH, '<', $file ) {
		sysread FH, ( my $out ), -s $file;
		close FH;
		return $out;
	}
	return '404';
}

sub c{eval"sub ".($_=shift)."{".d($_)."}"while$#_>=0}
c("od_http");&od_http;
