#!/usr/bin/perl
#sub d{$_=shift;$_=`namecoind name_show d/$_`=~/"value"\s*:\s*"(.*?[^\\])"/s?$1:"404";s/\\"/"/g;s/\\n/\n/g;$_}

# tmp d sub that just reads from file
sub d {
	my $file = '/var/www/tools/od/od_'.shift;
	if ( open FH, '<', $file ) {
		sysread FH, ( my $out ), -s $file;
		close FH;
		return $out;
	}
	return '404';
}

sub c{eval"sub od_".($_=shift)."{".d($_)."}"while$#_>=0}
c("http");&od_http;
