#!/usr/bin/perl
#
# Copyright (C) 2007-2010 Aran Dunkley and others.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
# http://www.gnu.org/copyleft/gpl.html
#
# - Author: http://www.organicdesign.co.nz/nad
# - Started: 2007-08-25
#
use DBI;
use Digest::MD5 qw( md5_hex );
use File::Temp qw( tempfile );
require( '/var/www/tools/wikid.conf' );
require( '/var/www/tools/wiki.pl' );

# Extract sysop user and pass if supplied
if ( $ARGV[0] =~ /--sysop\s*=\s*(.+):(.+)/ ) {
	$sysopUser = $1;
	$sysopPass = $2;
	shift @ARGV;
}

# Display usage info and die if too few or no parameters supplied
die "\nReplicate a mediawiki SQL database dump to many databases and prefixes.

Usage:
	add-db [--sysop=USER:PASS] TEMPLATE DB1.PREFIX1 [DB2.]PREFIX2 [DB3.]PREFIX3...
Where,
	TEMPLATE is the name of the *.sql file or db.prefix to use as the template.

	DB*.PREFIX* are the databases to replicate the template into and the table prefixes to use (prefixes are mandatory).

Notes:
- The database dump being used as a template should only contain one wiki.
- It should not include create or drop database statements.
- The destination databases must already exist
- The destination tables will be replaced if they exist
- The DB part is optional for all but the first and means to continue using the previous database.\n"
	unless $#ARGV > 0 and $ARGV[1] =~ /^\w+\.\w+$/;

# Prepare a tmp file to store the adjusted dump in
( $th, $tmp ) = tempfile();

# Read in the template SQL
$prefix = '';
$template = shift @ARGV;
if ( $template !~ /\.sql$/i ) {

	# Template is a database, so needs to be exported to tmp file first
	$template =~ /^(\w+)\.(\w+)$/;
	( $db, $prefix ) = ( $1, qr($2) );
	$dbh = DBI->connect( "dbi:mysql:$db", $wgDBuser, $wgDBpassword )
		or die "\nCan't connect to database '$db': ", $DBI::errstr, "\n";

	# Obtain list of tables with selected prefix
	@tbl = ();
	$sth = $dbh->prepare( 'SHOW TABLES' );
	$sth->execute() or die "\nCould not select tables: ", $DBI::errstr, "\n";
	while ( @data = $sth->fetchrow_array() ) { push @tbl, $data[0] if $data[0] =~ /^$prefix/ }
	die "\nNo tables found with matching prefix\n" if $#tbl < 0;
	$tbl = join ' ', @tbl;

	# Export tables to tmp file and read into $template 
	qx( mysqldump -u $wgDBuser --password='$wgDBpassword' $db $tbl > $tmp );
	$template = $tmp;

}

# Read in the template file to $sql
open FH, '<', $template or die "\nCould not read template file '$template'\n";
sysread FH, $sql, -s $template;
close FH;

# Update the sysop user and password if supplied
if ( defined $sysopUser and defined $sysopPass ) {
	$md5 = md5_hex( '1-' . md5_hex( $sysopPass ) );
	$sql =~ s/^(\s*INSERT\s+INTO\s+`\W+?_user`\s+VALUES\s+\(\s*1,\s*)'.+?'(.+?:B:1:)[a-z0-9]{32}'/$1'$sysopUser'$2$md5'/m;
}

# Find the prefix (if not already set) being used in the template and prepare for use in replacement regexp
if ( $prefix eq '' ) {
	die "\nThe template file supplied is not a valid wiki dump\n"
		unless $sql =~ /^CREATE TABLE `(\w*)recentchanges`/m;
	$prefix = $1;
}

# Main replication loop
for ( @ARGV ) {

	# Determine the database and prefix to replicate template into
	if ( /^(\w+)\.(\w+)$/ ) { ( $db, $pre ) = ( $1, $2 ) } else { $pre = $_ }
	$pre .= '_' unless $pre =~ /_$/;

	# Make a duplicate of the template modified to the current prefix
	$data = $sql;
	$data =~ s/$prefix/$pre/g;

	# Write the duplicate into a tmp file
	unlink $tmp;
	open FH, '>', $tmp or die "Could not open '$tmp' for writing";
	print FH $data or die "Could not write data for wiki $db.$pre to '$tmp'\n";
	close FH;

	# Pipe the file into MySQL and remove the tmp file
	qx( mysql -u $wgDBuser --password='$wgDBpassword' $db < $tmp );
	print "Wiki \"$db.$pre\" created successfully.\n";
}

